### PR TITLE
Add continuous integration (based on appveyor)

### PR DESCRIPTION
**Pull request by sykhro**
After enabling AppVeyor, this will automatically build every commit and upload the binaries.
Useful for people who don't have access to Visual Studio and also acts as a mirror.

`ENABLE_AUOSETUP` should be a compile-time variable, since the required files for the setup are missing from the repo.

It can be configured to upload to GitHub releases by adding the following:
```
deploy:
  release: x264guiEx-v$(appveyor_build_version)
  description: ' '
  provider: GitHub
  auth_token:
    secure: *GITHUB TOKEN*
  artifact: /x264guiEx-latest.zip
  draft: false
  prerelease: false
  on:
    branch: master
    # deploy on tag push only (don't make a new release for *every* commit)
    appveyor_repo_tag: true
```
---
AppVeyorを有効にすると、自動的にすべてのコミットがビルドされ、バイナリがアップロードされます。
Visual Studioへのアクセス権がなく、ミラーとしても機能する人に便利です。
`ENABLE_AUOSETUP`はコンパイル時の変数でなければなりません。セットアップに必要なファイルがリポジトリにないからです。

私の悪い日本人のために申し訳ありません。

### CODE REVIEW

**Comment by rigaya** [comment]
Thank you for your request.
It would be nice to have automatic build on each tag.

- About ENABLE_AUOSETUP flag
This flag was intended as test usage only, so build without ENABLE_AUOSETUP flag is not tested completely. Therefore, it is prefered not to be disabled on release build.
I have added the missing file to the repository. Would you mind merging c23b5823 and re-enable ENABLE_AUOSETUP?

- intrin.h in VS2017
I think this problem in VS2017 is caused by "get_run_bat_idx()" in "auo_conf.h", I'd rather prefer intrin.h to be included in "auo_conf.h", and not in "auo.h".

**Comment by sykhro** [comment]
Thank you for your review, I moved the include and restored the setup. Also, build is triggered only on tagged commits now.

**Comment by rigaya** [comment]
Thank you for your contribution!

**Comment by rigaya** [comment]
I've triggered the build manually on AppVeyor for test, and realized having many warnings related to character code. 7z archieve with the binary included was built properly, but with the Japanese characters not correct.

```
     2>frm\auo_error.cpp(157): warning C4566: character represented by universal-character-name '\u3092' cannot be represented in the current code page (1252) [C:\projects\x264guiex\x264guiEx\x264guiEx.vcxproj]
     2>frm\auo_error.cpp(157): warning C4566: character represented by universal-character-name '\u30AA' cannot be represented in the current code page (1252) [C:\projects\x264guiex\x264guiEx\x264guiEx.vcxproj]
     2>frm\auo_error.cpp(157): warning C4566: character represented by universal-character-name '\u306B' cannot be represented in the current code page (1252) [C:\projects\x264guiex\x264guiEx\x264guiEx.vcxproj]
```

I think switching the environment to CP1252 to CP932 will do, I'll test later (when I have time).

**Comment by sykhro** [comment]
sorry about this, I didn't notice
you can add this to the .yml:
```
init:
- ps: Set-WinSystemLocale ja-JP
- ps: Start-Sleep -s 5
- ps: Restart-Computer
- git config --global core.autocrlf input
```

**Comment by rigaya** [comment]
Changing codepage was successfull, and now the binary is uploaded to [release](https://github.com/rigaya/x264guiEx/releases/tag/2.56v2)!

Thank you very much.

**Pull request merged**
